blank_issues_enabled: false
contact_links:
  - name: Questions and usage help
    url: https://github.com/techwizrd/calmplots/discussions
    about: Please use Discussions for Q&A and show-and-tell posts.
